[package]
name = "bolt_ts_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
rustc-hash = { workspace = true }
bumpalo = { version = "3.16.0" }
bitflags = "2.6.0"
xxhash-rust = { version = "0.8.12", features = ["xxh3", "const_xxh3"] }
bolt_ts_errors = { path = "../errors" }
bolt_ts_span = { path = "../span" }
bolt_ts_lib = { path = "../lib" }
project-root = "0.2.2"
thin-vec = { workspace = true }
stacker = "0.1"
include_dir = "0.7.3"

[dev-dependencies]
expect-test = "1.2.2"
compile-test = { path = "../compile-test" }

[build-dependencies]
project-root = "0.2.2"
