[package]
name = "bolt_ts_errors"
version = "0.1.0"
edition = "2024"

[dependencies]
miette = { workspace = true }
thiserror = { version = "1.0.56" }
bolt_ts_span = { path = "../span" }
ropey = "1.5.0"
relative-path = "2.0.1"
bolt_ts_diag_derive = { path = "../diag-derive" }
