[package]
name = "bolt_ts_span"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { workspace = true }
rustc-hash = { workspace = true }
bolt_ts_fs = { path = "../fs" }
bolt_ts_utils = { path = "../utils" }
bolt_ts_atom = { path = "../atom" }
