[package]
name = "bolt_ts_arena"
version = "0.1.0"
edition = "2024"

[dependencies]
la-arena = { version = "0.3.1" }
typed-arena = { version = "2.0.2" }
bumpalo = { version = "3.16.0" }
bumpalo-herd = "0.1.2"
