[package]
name = "bolt_ts_atom"
version = "0.1.0"
edition = "2024"

[dependencies]
bolt_ts_utils = { path = "../utils" }

rustc-hash = { workspace = true }
paste = { workspace = true }
nohash-hasher = { workspace = true }
