[package]
name = "bolt_ts_atom"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = { workspace = true }
xxhash-rust = { workspace = true, features = ["xxh3", "const_xxh3"] }
bolt_ts_utils = { path = "../utils" }
nohash-hasher = { workspace = true }
paste = { workspace = true }
