[package]
name = "rts_errors"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { workspace = true }
thiserror = { version = "1.0.56" }
rts_span = { path = "../span" }
ropey = "1.5.0"
relative-path = "1.9.3"
