[package]
name = "bolt_ts_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bolt_ts_compiler = { path = "../compiler" }
wasm-bindgen = "0.2"
serde = { workspace = true }
serde_json = { workspace = true }
