[package]
name = "bolt_ts_resolve"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
bolt_ts_fs = { path = "../fs" }
bolt_ts_atom = { path = "../atom" }
normalize-path = { workspace = true }
