name: CI
on: push
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Rust
      uses: moonrepo/setup-rust@v1.3
      with:
        inherit-toolchain: true
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: Run cargo test
      run: cargo test -q
    - name: Run wasm-pack build and test
      working-directory: crates/wasm
      run: |-
        cargo install wasm-pack
        wasm-pack test --node
  javascript-check-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Rust
      uses: moonrepo/setup-rust@v1.3
      with:
        targets: wasm32-wasip1-threads
        inherit-toolchain: true
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: true
    - name: Run pnpm build packages
      run: pnpm build
    - name: Run biome format and lint check
      run: |-
        npx biome format
        npx biome lint
    - name: Test packages under headless
      uses: coactions/setup-xvfb@v1
      with:
        run: pnpm test
  codspeed-benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Rust
      uses: moonrepo/setup-rust@v1.3
      with:
        bins: cargo-codspeed
        inherit-toolchain: true
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
    - name: Run CodSpeed build
      run: cargo codspeed build -m walltime
    - name: Run CodSpeed benchmark
      uses: CodSpeedHQ/action@v4
      with:
        run: cargo codspeed run bench -m walltime
        token: ${{ secrets.CODSPEED_TOKEN }}
        mode: walltime
        cache-instruments: 'false'
